#!/usr/bin/env bash
set -euo pipefail

# edict official clean baseline + local P0/P1/P2 overlay replay
# Runs in a disposable worktree. Applies selected local overlay files by phase.

ROOT="/root/.openclaw/workspace/edict"
UPSTREAM="/root/.openclaw/workspace/_third_party/cft0808-edict-upstream"
WORKTREES_ROOT="/root/.openclaw/workspace/_worktrees"
TS="$(date +%Y%m%d-%H%M%S)"
WT="$WORKTREES_ROOT/edict-official-overlay-replay-$TS"
LOG="$ROOT/overlays/edict/scripts/replay-$TS.log"
SUMMARY="$ROOT/overlays/edict/scripts/replay-$TS.summary.json"

mkdir -p "$WORKTREES_ROOT" "$(dirname "$LOG")"

exec > >(tee -a "$LOG") 2>&1

echo "[replay] upstream=$UPSTREAM"
echo "[replay] local=$ROOT"
echo "[replay] worktree=$WT"

git -C "$UPSTREAM" worktree add --detach "$WT" HEAD
cleanup() {
  git -C "$UPSTREAM" worktree remove --force "$WT" >/dev/null 2>&1 || true
}
trap cleanup EXIT

copy_path() {
  local rel="$1"
  if [ -e "$ROOT/$rel" ]; then
    mkdir -p "$(dirname "$WT/$rel")"
    rm -rf "$WT/$rel"
    cp -a "$ROOT/$rel" "$WT/$rel"
    echo "[apply] $rel"
  else
    echo "[skip-missing] $rel"
  fi
}

verify_python_compile() {
  echo "[verify] python compile"
  local files=(
    dashboard/server.py
    dashboard/court_discuss.py
    scripts/refresh_live_data.py
    scripts/sync_from_openclaw_runtime.py
    scripts/apply_model_changes.py
    scripts/autopsy_draft.py
    scripts/sync_agent_config.py
    scripts/sync_officials_stats.py
    scripts/utils.py
    edict/backend/app/services/task_service.py
    edict/backend/app/services/notification_service.py
    edict/backend/app/workers/dispatch_worker.py
    edict/backend/app/workers/orchestrator_worker.py
    edict/backend/app/api/tasks.py
    edict/backend/app/api/legacy.py
  )
  local existing=()
  local rel
  for rel in "${files[@]}"; do
    [ -f "$rel" ] && existing+=("$rel") || echo "[compile-skip-missing] $rel"
  done
  python3 -m py_compile "${existing[@]}"
}

verify_shell_syntax() {
  echo "[verify] shell syntax"
  bash -n install.sh
  bash -n start.sh
  bash -n edict.sh
  bash -n scripts/run_loop.sh
  [ ! -f scripts/doctor_edict.sh ] || bash -n scripts/doctor_edict.sh
}

verify_frontend_build() {
  echo "[verify] frontend build"
  (
    cd edict/frontend
    if [ ! -x node_modules/.bin/tsc ]; then
      echo "[verify] frontend deps missing; running npm install"
      npm install
    fi
    npm run build
  )
}

verify_frontend_audit() {
  echo "[verify] frontend npm audit"
  (
    cd edict/frontend
    if [ ! -d node_modules ]; then
      echo "[verify] frontend deps missing; running npm install"
      npm install
    fi
    npm audit --audit-level=moderate
  )
}

verify_behavior() {
  echo "[verify] behavior pytest"
  python3 -m pytest tests/test_server.py tests/test_autopsy_draft.py tests/test_sync_governance_samples.py -q
}

write_summary() {
  local status="${1:-passed}"
  local behavior_result="${2:-not-run}"
  local baseline_head="${BASELINE_HEAD:-unknown}"
  mkdir -p "$(dirname "$SUMMARY")"
  python3 - "$SUMMARY" <<PY
import json, sys
summary = {
    'schema_version': '1.0',
    'status': '$status',
    'timestamp': '$TS',
    'upstream': '$UPSTREAM',
    'local': '$ROOT',
    'worktree': '$WT',
    'log': '$LOG',
    'summary': '$SUMMARY',
    'baseline_head': '$baseline_head',
    'phases': {
        'official_baseline': ['python_compile', 'frontend_build'],
        'p0': ['copy_overlay_files', 'python_compile', 'shell_syntax', 'frontend_audit', 'frontend_build'],
        'p1': ['copy_overlay_files', 'python_compile', 'shell_syntax'],
        'p2': ['copy_overlay_files', 'existence_checks'],
        'final_behavior': ['$behavior_result'],
    },
    'behavior_command': 'python3 -m pytest tests/test_server.py tests/test_autopsy_draft.py tests/test_sync_governance_samples.py -q',
    'p0_files': ${P0_JSON:-[]},
    'p1_files': ${P1_JSON:-[]},
    'p2_files': ${P2_JSON:-[]},
    'notes': [
        'Generated by overlays/edict/scripts/replay-official-overlay.sh',
        'Clean worktree is removed after run; log and summary are durable artifacts.'
    ],
}
path = sys.argv[1]
with open(path, 'w', encoding='utf-8') as f:
    json.dump(summary, f, ensure_ascii=False, indent=2)
    f.write('\n')
print(f'[replay] SUMMARY {path}')
PY
}

array_json() {
  python3 - "$@" <<'PY'
import json, sys
print(json.dumps(sys.argv[1:], ensure_ascii=False))
PY
}

cd "$WT"
BASELINE_HEAD="$(git rev-parse --short HEAD)"
echo "[replay] baseline head=$BASELINE_HEAD"

echo "[phase] official baseline"
verify_python_compile
verify_frontend_build

P0=(
  dashboard/server.py
  dashboard/court_discuss.py
  install.sh
  start.sh
  edict.sh
  edict/frontend/package.json
  edict/frontend/package-lock.json
  scripts/run_loop.sh
  scripts/apply_model_changes.py
  scripts/autopsy_draft.py
  scripts/sync_agent_config.py
  scripts/sync_from_openclaw_runtime.py
  scripts/sync_officials_stats.py
  scripts/refresh_live_data.py
  scripts/sync_governance_samples.py
  scripts/rebuild_task_views.py
  scripts/export_backend_tasks_to_legacy_json.py
  scripts/guard_openclaw_sessions.py
  scripts/utils.py
  edict/backend/app/api/tasks.py
  edict/backend/app/api/legacy.py
  edict/backend/app/models/task.py
  edict/backend/app/services/task_service.py
  edict/backend/app/services/notification_service.py
  edict/backend/app/workers/__init__.py
  edict/backend/app/workers/dispatch_worker.py
  edict/backend/app/workers/orchestrator_worker.py
  edict/migration/versions/002_add_outbox_events.py
  tests/test_server.py
  tests/test_autopsy_draft.py
  tests/test_sync_governance_samples.py
)
P0_JSON="$(array_json "${P0[@]}")"

echo "[phase] apply P0"
for rel in "${P0[@]}"; do copy_path "$rel"; done
verify_python_compile
verify_shell_syntax
verify_frontend_audit
verify_frontend_build

P1=(
  scripts/doctor_edict.sh
  scripts/check_backend_prereqs.sh
  scripts/manage_backend_infra.sh
  scripts/run_backend_component.sh
  scripts/run_backend_migrations.sh
  scripts/setup_backend_runtime.sh
  deploy
  docs/current-progress-board.md
  docs/closeout.md
  docs/governance-upgrade-map.md
  docs/review-correction-notes.md
  docs/task-dispatch-architecture.md
  docs/backend-host-native-productionization.md
)
P1_JSON="$(array_json "${P1[@]}")"

echo "[phase] apply P1"
for rel in "${P1[@]}"; do copy_path "$rel"; done
verify_python_compile
verify_shell_syntax

P2=(
  docs/JJC-20260416-001-sansheng-governance-executable-review.md
  docs/JJC-20260416-001-task-division-plan.txt
  docs/openclaw-feishu-p2p-hotfix.md
  docs/edict-official-overlay-alignment-20260508.md
  docs/edict-completion-status-20260426.md
  docs/natural-governance-sample-thickening-plan.md
  docs/openclaw-feishu-bypass-compensation-runbook.md
  docs/openclaw-feishu-bypass-duty-template.md
  docs/ARCHITECTURE.md
  docs/FRONTEND.md
  docs/RELIABILITY.md
  docs/SECURITY.md
  docs/exec-plans
  docs/plans
  docs/state
  docs/templates
  overlays/edict
)
P2_JSON="$(array_json "${P2[@]}")"

echo "[phase] apply P2"
for rel in "${P2[@]}"; do copy_path "$rel"; done

test -f docs/JJC-20260416-001-sansheng-governance-executable-review.md
test -f docs/JJC-20260416-001-task-division-plan.txt
test -f overlays/edict/upgrade-patches/replay-queue-20260508.md

verify_behavior
write_summary "passed" "pytest_passed"

echo "[replay] DONE log=$LOG summary=$SUMMARY"
